### ISSUE TITLE
#1354 Myページ・購入履歴詳細のメール件名に店舗名が付与されない場合がある

### ISSUE THREAD

**Issue by hoand-vn** [eccubevn/ec-cube#1]
Myページ・購入履歴詳細のメール件名に店舗名が付与されない場合がある #1354    https://github.com/EC-CUBE/ec-cube/issues/1354

**Comment by lqdung-lockon** [comment]
There is an error, pleases check:
https://travis-ci.org/lqdung-lockon/ec-cube/builds/142647614
