### ISSUE TITLE
The block.twig can not get the {http_cache} (esi) parameter

### ISSUE THREAD

**Issue by ryo-endo** [eccubevn/ec-cube#114]
The block.twig can not get the {http_cache} (esi) parameter.

Product: Code
Category: GUI

ref:
https://github.com/EC-CUBE/ec-cube/blob/experimental/sf/src/Eccube/Resource/template/default/block.twig#L25
https://github.com/EC-CUBE/ec-cube/blob/experimental/sf/app/config/eccube/packages/framework.yaml#L24

**Comment by ryo-endo** [comment]
@hoand-vn これ、LVNのQAシートから転記した内容です。
もう少し詳しく内容を記載お願いできますか？

**Comment by hoand-vn** [comment]
with Block , not use controller at now, so maybe resolve problem.
https://github.com/EC-CUBE/ec-cube/blob/experimental/sf/src/Eccube/Resource/template/default/block.twig#L13
