### ISSUE TITLE
[3n]-[Plugin]-[Core] Can not run unit-web test for plugin

### ISSUE THREAD

**Issue by hoand-vn** [eccubevn/ec-cube#117]
## 概要(Overview)
- Can not run unit-web test for plugin

## 期待する内容(Expect)  or 要望 (Requirement)
- When run web test for plugin:
    - Core still not build route of plugin ( for test environment only )
    - So have error : page not found

### 環境 (environment)
+ EC-CUBE: 3.N.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/blob/experimental/sf/src/Eccube/DependencyInjection/EccubeExtension.php#L33

**Comment by lqdung-lockon** [comment]
Fixed => close it.
