### ISSUE TITLE
[3n]-[Plugin]-[Core] Error message " not found route" when install/ enable plugins

### ISSUE THREAD

**Issue by hoand-vn** [eccubevn/ec-cube#119]
## 概要(Overview)
 Error message " not found route" when install/ enable plugins

## 期待する内容(Expect)  or 要望 (Requirement)
- When install/enable/remove/disable plugin
- Cache was be cleared so can not find route in cache -> error
Solution :
- Redirect to re-create cache again.
But in unit-test still have problem

### 環境 (environment)
+ EC-CUBE: 3.N.x
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by ryo-endo** [comment]
@hoand-vn 
このコミットで、修正されていないでしょうか？
https://github.com/EC-CUBE/ec-cube/commit/397e756be852bd8d4a3b9acd399c4dc419c3af7f
再確認をしてもらいたいです。

**Comment by lqdung-lockon** [comment]
@ryo-endo -san,
It still not fix for this case:
https://github.com/EC-CUBE/ec-cube/blob/10bdd16a9b6436ad7696131187810b98f68f9c05/tests/Eccube/Tests/Service/PluginServiceWithEntityExtensionTest.php#L50

**Comment by lqdung-lockon** [comment]
answered => close
