### ISSUE TITLE
[3n]-[Plugin]-[OrderPdf]- Update new library, auto load library

### ISSUE THREAD

**Issue by toannguyen-lockon** [eccubevn/ec-cube#124]
## 概要 (Overview)
- I should change FPDI library, tcpdf to newer version ?
- Unable auto load tcpdf information with current version.

## 期待 す る 内容 (Expected) or 要 望 (Required)
- Can automatically load plugin library (the current version is based on the basic standard).
- Update the library to a newer version (such as the php class library)

## 再現 手 順 (Procedure)
- None

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
- PostgreSQL x.x.x
- MySQL x.x.x

**Comment by hoand-vn** [comment]
integration with CORE => close this Q&A
