### ISSUE TITLE
[3n]-[Plugin]-[#1633] Where to show plugin fields

### ISSUE THREAD

**Issue by toannguyen-lockon** [eccubevn/ec-cube#126]
## 概要(Overview)
- New style guide for plugin after enabled:	
	Form add -> show plugin fields ahead submit button	
	Form edit -> can append plugin fields to inline form
        Ref: https://i.gyazo.com/12a62a6e6ed64d92fda394bb6da390d7.png

I have seen this problem here => No16: https://docs.google.com/spreadsheets/d/1E_uiIw0tI7dyUcFgRSWJ1zut-1HV9XC9_oxLji3Yu7Q/edit#gid=506826524
But I'm thinking of doing something more flexible.

## 期待する内容(Expect)  or 要望 (Requirement)
My suggest is:
	Should add slot to display plugin fields to form edit inline
	It is also possible to arrange the locations of the fields to be displayed
	
Q&A:
	Solve this problem in this way, or you have a better way, please tell me ?
I am waiting for your answer.

## 再現手順(Procedure)
- None

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by nhpkhanh-lk** [comment]
## 概要(Overview)
プラグインを有効した時の画面に関して、確認したいです。
　現状：
　・Form 新規作成 ：Input textbox→新規作成→plugin field
　・Form 編集 ：Input textbox→決定→キャンセル
　参照: https://i.gyazo.com/12a62a6e6ed64d92fda394bb6da390d7.png

インライン表示に関して、以前のQ&Aを見つけました。
No16: https://docs.google.com/spreadsheets/d/1E_uiIw0tI7dyUcFgRSWJ1zut-1HV9XC9_oxLji3Yu7Q/edit#gid=506826524
しかし、これと違う、より良いやりかたがないと考えています。

## 期待する内容(Expect) or 要望 (Requirement)
Fieldsの順番を変更するという案
　・Form 新規作成 ： Input textbox→plugin field→新規作成
　・Form 編集 ： Input textbox→plugin field→決定→キャンセル

ご確認。宜しくお願い致します。
I am waiting for your answer.

## 再現手順(Procedure)
None
## 環境 (environment)
EC-CUBE: 3.x.x
PHP: x.x.x
DB:
PostgreSQL x.x.x
MySQL x.x.x
関連情報 (Ref)

**Comment by ryo-endo** [comment]
@toannguyen-lockon 
期待する内容 に書いてある順番で良いと思います。

**Comment by hoand-vn** [comment]
as your comment :  https://github.com/eccubevn/ec-cube/tree/experimental/sf-fix-issue-126
