### ISSUE TITLE
[3n][plugin] Change content in template

### ISSUE THREAD

**Issue by hoand-vn** [eccubevn/ec-cube#127]
## 概要(Overview)
- With current solution : Use EccubeTwigBlock in FrontEnd
    - We can : Addition a apartment into template
    - We can NOT do something:
       - Edit apartment of template
       - Delete apartment of template
 - Change template in Admin still using replace_string ( same 3.0 version )
     
## 再現手順(Procedure)
- With Plugin Tag Category, when show detail of product at Frontend
   - Replace text of Tag to URL of Tag => Can not implement

**Comment by nhpkhanh-lk** [comment]
## 概要(Overview)
今回のテンプレートであると、プラグインでコンテンツを変更した時、以下の問題があります。
現状として Use EccubeTwigBlock in FrontEnd
　■できること： Addition a apartment into template
　■でき**ない**こと：
　　・Edit apartment of template
　　・Delete apartment of template
　　・Change template in Admin still using replace_string ( same 3.0 version )

## 期待する内容(Expect) or 要望 (Requirement)
　ソリューションを教えてください。
　Replace stringsを考えています。

## 再現手順(Procedure)
　商品タグ機能拡張プラグインを有効
　フロント画面でタグをTextからURLに変更すると
　=> Can not implement

## 環境 (Environment)

## 関連情報 (Ref)

**Comment by chihiro-adachi** [comment]
既存のHTML要素を変更する場合は、TemplateEvent::addSnippetを使用してください。

**Comment by hoand-vn** [comment]
@chihiro-adachi could give example ?

**Comment by ryo-endo** [comment]
@hoand-vn FYI https://github.com/EC-CUBE/sample-payment-plugin#%E7%94%BB%E9%9D%A2%E3%81%B8%E3%81%AE%E4%BB%8B%E5%85%A5%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by hoand-vn** [comment]
ah i see,

it's mean, we will using JavaScript at client to change anything.

**Comment by hoand-vn** [comment]
using Snippet for all cases
