### ISSUE TITLE
[3n][Core] Missing auto render form extension

### ISSUE THREAD

**Issue by nhpkhanh-lk** [eccubevn/ec-cube#128]
## 概要(Overview)
Some templates are missing auto render form extension as below.
いくつかのコアのテンプレートには以下のコードがない状態。
```
{% for f in searchForm %}
    {# auto_render有効時に出力 #}
    {% if f.vars.eccube_form_options.auto_render %}
        {# form_themeが設定されている場合にthemeを適用 #}
        {% if f.vars.eccube_form_options.form_theme %}
            {% form_theme f f.vars.eccube_form_options.form_theme %}
        {% endif %}
        {{ form_row(f) }}
    {% endif %}
{% endfor %}
```
## 期待する内容(Expect)  or 要望 (Requirement)
Add this code into templates which are missing
このコードがないテンプレートにコードを追加する。
↓ブランチをご参考ください。
https://github.com/eccubevn/ec-cube/tree/experimental/sf-enable-form-auto-render

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by ryo-endo** [comment]
PullRequestください。

**Comment by hoand-vn** [comment]
using PR of Adachi san : https://github.com/EC-CUBE/ec-cube/pull/3242
