### ISSUE TITLE
[3n][core] Have a bug : "Could not convert database value xxx to Doctrine Type datetimetz. Expected format: Y-m-d H:i:s"

### ISSUE THREAD

**Issue by hoand-vn** [eccubevn/ec-cube#131]
## 概要(Overview)
- When go to Admin page, CSV setting page : /admin/setting/shop/csv
- Will have a error about format of datetime

## 期待する内容(Expect)  or 要望 (Requirement)
- Can work well with SQLite.
- Work well with Travis.

## 再現手順(Procedure)
- When go to Admin page, CSV setting page : /admin/setting/shop/csv
- Will have a error : "Could not convert database value "2017/3/7 10:14" to Doctrine Type datetimetz. Expected format: Y-m-d H:i:s"
- Occur bug on SQLite

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x : None 
  - MySQL x.x.x : None
  - Sqlite

**Comment by ryo-endo** [comment]
@hoand-vn maybe fix this PR
https://github.com/EC-CUBE/ec-cube/pull/3342

**Comment by hoand-vn** [comment]
fixed with https://github.com/EC-CUBE/ec-cube/pull/3342
