### ISSUE TITLE
[CORE][PLUGIN] ]コントローラがないブロックはフックできない

### ISSUE THREAD

**Issue by lqdung-lockon** [eccubevn/ec-cube#136]
## 概要(Overview)
There is no way to hook into a block without the controller

## 期待する内容(Expect)  or 要望 (Requirement)
Expected:
1. Core has an event to hook to the `include/extends` function in twig
or
2. Core has events about category repository.

## 再現手順(Procedure)
SmartCategory plugin, It hooks into `Block/category.twig`

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

## 関連情報 (Ref)
SmartCategory plugin

**Comment by ryo-endo** [comment]
@lqdung-lockon 
問題認識しました。
すぐに問題を解決することは難しそうです。

この問題解決しないとSmartCategory が完了できないですよね？

**Comment by ryo-endo** [comment]
いまは `@Template` で指定したtwigファイルだけが対象なので、コントローラのないBlockは、拡張ができない。

**Comment by hoand-vn** [comment]
Yes, we should stop this plugin unstill have solution.
