### ISSUE TITLE
[3n] - [Plugin] - Metaタグがありません

### ISSUE THREAD

**Issue by nhpkhanh-lk** [eccubevn/ec-cube#137]
## 概要(Overview)
3.nでは以下のようなMetaタグをない。
（Version 3.n does not automatically display the meta tag as an image below）
https://i.gyazo.com/4ab7ea208542f0ffc408764295aba348.png

## 期待する内容(Expect)  or 要望 (Requirement)
いくつかの選択があります。
① default_frameフォームに以下のコードを追加する
（Add the code below to the core soucre's default_frame form）
{% if Page.meta_tags is not empty%}
{{Page.meta_tags | raw}}
{% endif%}

② addSnipet
③ String replacement

他に、適切なやり方があったら、教えてください。

### 環境 (environment)
+ EC-CUBE: 3.x.x
+ PHP: x.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

**Comment by toannguyen-lockon** [comment]
I have used `$event->addAsset();`  and I think it's ok, please let me know if you have other comments.

**Comment by ryo-endo** [comment]
@toannguyen-lockon 
意図せず消えているようです。
default_frame.twigに追加して本体にPullRequestお願いします。

**Comment by ryo-endo** [comment]
fix this
https://github.com/EC-CUBE/ec-cube/commit/1ddfca0cb9e4e0e02c2d75e7caa6356b79516742#diff-7cefac9fd3759d999afb711a36b6dad9R31
