### ISSUE TITLE
[CORE][FRONT][MYPAGE] メール配信履歴一覧に複数のメールがある時、一つずつ開けることができない 

### ISSUE THREAD

**Issue by lqdung-lockon** [eccubevn/ec-cube#141]
## 概要(Overview)
In mypage history, when you have 2 emails, if you click on one email, both them will expand all.

## 期待する内容(Expect)  or 要望 (Requirement)
Just extend the email is clicked.

## 再現手順(Procedure)
1. Purchase an item and complete it.
2. Go to order management and send another email, for example, email shipped.
3. Go to mypage history and click on one email to see it.
=> Bug: expand all 2 emails
- Expected: Just extend the email is clicked.

### 環境 (environment)
4.0

## 関連情報 (Ref)
![image](https://user-images.githubusercontent.com/18606264/43817273-c537ea5e-9b02-11e8-8d22-99873a9ec4f3.png)

**Comment by nhpkhanh-lk** [comment]
## 概要(Overview)
メール配信履歴一覧にメールが2つ以上ある時、一つをクリックしたが、全部が開くことになっている。

## 期待する内容(Expect)  or 要望 (Requirement)
クリックされた内容だけが表す　


## 再現手順(Procedure)
1. フロントで商品購入を行う
2. 管理画面>受注一覧でメールを配信する
3. フロント>マイページに行って、メール配信履歴一覧を確認
=> 一つをクリックしたが、全部が開くことになっている。

### 環境 (environment)
4.0

## 関連情報 (Ref)
![image](https://user-images.githubusercontent.com/18606264/43817273-c537ea5e-9b02-11e8-8d22-99873a9ec4f3.png)

**Comment by ryo-endo** [comment]
fixed
